### ISSUE TITLE
Can't run on RaspberryPi: Error Cannot find module './uws_linux_arm_88.node'

### ISSUE THREAD

**Issue by adelinn** [Novage/wt-tracker#37]
When I try to run wt-tracker with `node dist/run-uws-tracker.js config.json` I get:
`/home/pi/wt-tracker/node_modules/uWebSockets.js/uws.js:31
                throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
                ^

Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_linux_arm_88.node'
Require stack:
- /home/pi/wt-tracker/node_modules/uWebSockets.js/uws.js
- /home/pi/wt-tracker/dist/uws-tracker.js
- /home/pi/wt-tracker/dist/run-uws-tracker.js
    at /home/pi/wt-tracker/node_modules/uWebSockets.js/uws.js:31:9
    at Object.<anonymous> (/home/pi/wt-tracker/node_modules/uWebSockets.js/uws.js:33:3)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/pi/wt-tracker/dist/uws-tracker.js:33:26)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)`

NodeJs v15.8.0
NPM v7.5.3

**Comment by adelinn** [comment]
Actually this is an issue with uWebSockets I think.

**Comment by adelinn** [comment]
If anyone is looking for a solution to this, looks like uWebSockets.js wasn't built for arm yet. I built it and you can find the files in the pull request below. https://github.com/uNetworking/uWebSockets.js/pull/453/commits/5055801744a3ed1d69653ff840544c6fbad34ccd
